#!/usr/bin/env python3
import json
from pathlib import Path

lang_name = "däμbenscrypt"

config = {}
config_name = ".{}.json".format(lang_name)

wabt = Path(input("wabt path (default: none): "))
if wabt.exists():
  config["wabt_path"] = str(wabt)
else:
  raise ValueError("wabt directory doesn't exist")

with open(config_name, 'w') as out:
  json.dump(config, out)
  print("Installation was successful")
